name: GitHub Actions Demo
on: [push]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"

  build:
    needs: welcome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build ActionsKataExample
        
  test:
    needs: [welcome, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet test ActionsKataExample.Tests
        
  publish:
    needs: [welcome, build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet publish ActionsKataExample
