name: GitHub Actions Demo
on: [push]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build ActionsKataExample
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - run: dotnet test ActionsKataExample.Tests
        
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - run: dotnet publish ActionsKataExample
